side-project-drrr/backend

drrr-api/src/main/java/com/drrr/alarm/controller/PushAlarmController.java
drrr-api/src/main/java/com/drrr/auth/controller/AuthController.java
drrr-api/src/main/java/com/drrr/auth/payload/request/SignInRequest.java
drrr-api/src/main/java/com/drrr/auth/payload/response/SignInResponse.java
drrr-api/src/main/java/com/drrr/auth/payload/response/SignUpResponse.java
drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/error/GlobalExceptionHandler.java
drrr-api/src/main/java/com/drrr/recommand/controller/MemberPostWeightController.java
drrr-api/src/main/java/com/drrr/recommand/controller/RecommendController.java
drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-api/src/main/java/com/drrr/web/security/filter/JwtTokenValidationFilter.java

refactor: Lombok의 @NonNull을 javax의 @NotNull로 수정

refactor: Lombok의 @NonNull을 javax의 @NotNull로 수정

---

build.gradle
drrr-admin/build.gradle
drrr-admin/src/main/java/com/drrr/config/CorsConfig.java
drrr-admin/src/main/java/com/drrr/config/SwaggerConfig.java
drrr-admin/src/main/resources/application.yml
drrr-admin/src/test/java/com/drrr/controller/TemporaryTechBlogPostApiTest.java
drrr-admin/src/test/java/com/drrr/util/ApiTest.java
drrr-api/build.gradle
drrr-batch/build.gradle
drrr-domain/src/test/java/com/drrr/domain/techblogpost/repository/impl/TemporalTechBlogPostRepositoryImplTest.java

변경사항
1. jar파일 생성 가능하도록 변경
2. cors, swagger 설정 추가

refactor: admin 모듈 [cors, swagger] 설정 추가

---

drrr-api/src/main/java/com/drrr/alarm/controller/PushAlarmController.java
drrr-api/src/main/java/com/drrr/alarm/service/impl/ExternalMemberSubscriptionService.java
drrr-api/src/main/java/com/drrr/alarm/service/request/SubscriptionRequest.java
drrr-api/src/main/java/com/drrr/web/jwt/util/JwtProvider.java

[Refactor] 
- push controller에서 직접 repository 호출로 구독 정보 delete
- url mapping 변경 
- controller 반환 타입 void로 변경
- 필요없는 메서드 제거

refactor: push controller 관련 리팩토링

---

drrr-api/src/main/java/com/drrr/web/security/config/SecurityConfig.java
drrr-api/src/main/java/com/drrr/web/security/filter/JwtTokenValidationFilter.java

refactor: JWT 필터에 IP 제한 걸어둔 코드 제거, 서브모듈 필요없는 설정 제거한 것 반영, Security Config 쪽에  http request authorization으로 설정해둔 것은 나중에 어노테이션으로 관리하기 위해서 다 삭제

[REFACTOR] : Jwt filter와 security config 변경

---

drrr-api/src/test/java/com/drrr/member/MemberViewE2ETest.java
drrr-api/src/test/java/com/drrr/recommend/RecommendServiceE2ETest.java
drrr-api/src/test/java/com/drrr/techblogpost/TechBlogPostE2ETest.java
drrr-domain/src/main/java/com/drrr/domain/category/entity/CategoryWeight.java
drrr-domain/src/main/java/com/drrr/domain/category/service/InitializeWeightService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/MemberPreferredCategoryServiceModificationService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/MemberViewWeightService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/RecommendPostService.java
drrr-domain/src/test/java/com/drrr/domain/category/service/CategoryModificationTest.java
drrr-domain/src/test/java/com/drrr/domain/category/service/WeightValidationServiceTest.java
drrr-domain/src/test/java/com/drrr/domain/member/service/MemberViewWeightServiceTest.java
drrr-domain/src/test/java/com/drrr/domain/recommend/service/RecommendServiceTest.java
drrr-domain/src/test/java/com/drrr/domain/recommend/service/data/DummyDataFactory.java

refactor: 카테고리 가중치 테이블의 value 필드명 -> weightValue로 변경

refactor: 카테고리 가중치 테이블의 value 필드명 -> weightValue로 변경

---

drrr-domain/src/main/java/com/drrr/domain/log/entity/post/MemberPostLog.java

feat: 마지막으로 읽은 시간을 나타내는 필드 추가

---

drrr-api/src/main/java/com/drrr/auth/payload/request/GithubOAuth2Request.java
drrr-api/src/main/java/com/drrr/auth/payload/request/KakaoOAuth2Request.java
drrr-api/src/main/java/com/drrr/auth/payload/response/SignInResponse.java
drrr-api/src/main/java/com/drrr/auth/payload/response/SignUpResponse.java
drrr-api/src/main/java/com/drrr/recommand/dto/TechBlogPostDto.java

refactor: static method from 추가

refactor: static method from 추가

---

drrr-api/src/main/java/com/drrr/web/jwt/util/JwtProvider.java

chore: 발급자 명칭 변경

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java

chore: swagger 문서 내용 수정

---

drrr-api/src/main/java/com/drrr/auth/controller/AuthController.java

refactor: inline 처리

---

drrr-domain/src/main/java/com/drrr/domain/category/repository/CategoryWeightRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryWeightRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryWeightRepositoryImpl.java
drrr-infra/src/main/java/com/drrr/infra/notifications/kafka/webpush/WebPushProducer.java
drrr-infra/src/main/java/com/drrr/infra/push/repository/SubscriptionRepository.java

- 푸시 알림을 보내주기 위해 푸시 알림을 받을 member 조회가 가능한 custom repository 추가
-  1000명 단위로 비동기 푸시 알림 기능 추가

[ FEAT ] : 푸시 알림 기능 

---

drrr-domain/src/main/java/com/drrr/domain/category/repository/CategoryWeightRepository.java
drrr-domain/src/main/java/com/drrr/domain/member/repository/MemberRepository.java
drrr-domain/src/main/java/com/drrr/domain/member/service/UnregisterMemberService.java

[ FEAT ] : unregister 관련 api에서 논리적 삭제 기능 추가

[ FEAT ] : unregister 관련 api에서 논리적 삭제 기능 추가

---

drrr-api/src/main/java/com/drrr/recommand/service/impl/ExternalRecommendService.java
drrr-domain/src/main/java/com/drrr/domain/log/repository/CustomMemberPostLogRepository.java
drrr-domain/src/main/java/com/drrr/domain/log/repository/MemberPostLogRepository.java
drrr-domain/src/main/java/com/drrr/domain/log/repository/impl/CustomMemberPostLogRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/log/service/LogUpdateService.java

[ REFACTOR ] : 리팩토링 반영

---

drrr-domain/src/main/java/com/drrr/domain/category/service/MemberPreferredCategoryServiceModificationService.java

[ REFACTOR ] : 추가된 필드 업데이트 및 선호 카테고리 변경 후 가중치 검증도 추가

[ REFACTOR ] : 추가된 필드 업데이트 및 가중치 검증도 추가

---

drrr-api/src/main/java/com/drrr/recommand/controller/MemberPostWeightController.java
drrr-api/src/test/java/com/drrr/member/MemberViewE2ETest.java
drrr-domain/src/main/java/com/drrr/domain/category/service/RecommendPostService.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/service/TechBlogPostService.java

[ REFACTOR ] :  final list로 바꾸는 것 제거하고 변경 가능한 리스트로 생성, 테스트 케이스 줄이기, 컨트롤러 리팩토링

[ REFACTOR ] :  final list로 바꾸는 것 제거하고 변경 가능한 리스트로 생성

---

drrr-domain/src/main/java/com/drrr/domain/email/repository/EmailRepository.java
drrr-domain/src/main/java/com/drrr/domain/email/service/VerificationService.java
drrr-infra/src/main/java/com/drrr/infra/notifications/kafka/email/EmailProducer.java

[ REFACTORING ] : 이메일 인증 관련 리팩토링

[ REFACTORING ] : 이메일 인증 관련 리팩토링

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalCategoryService.java
drrr-domain/src/main/java/com/drrr/domain/category/entity/CategoryWeight.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryService.java

- category api controller 리펙토링, swagger 문서, pathVariable 변수명 등 변경
- 선호 카테고리에 대한 최소 가중치에 대한 버그 픽스
- 카테고리 api 관련 커스텀 리포지토리 추가

refactor: category api 리팩토링

---

drrr-api/src/main/java/com/drrr/alarm/controller/PushAlarmController.java
drrr-api/src/main/java/com/drrr/auth/controller/AuthController.java
drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/recommand/controller/MemberPostWeightController.java
drrr-api/src/main/java/com/drrr/recommand/controller/RecommendController.java
drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java

[ feat ] : jwt 토큰이 필요한 api에 어노테이션 추가

[ feat ] : jwt 토큰이 필요한 api에 어노테이션 추가

---

drrr-domain/src/main/java/com/drrr/domain/category/repository/CategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryService.java

[ refactor ] : 카테고리 api 리펙토링

---

drrr-api/src/main/java/com/drrr/category/service/impl/ExternalCategoryService.java
drrr-domain-redis/src/main/java/com/drrr/domain/category/service/RedisCategoryService.java

[ refactor ] : 레디스 관련 리펙토링

---

drrr-domain/src/main/java/com/drrr/domain/category/service/MemberViewWeightService.java
drrr-domain/src/main/java/com/drrr/domain/log/service/MemberPostLogService.java

[ feat ]: 새벽 12:00 기준, 넘기 전엔 다시 게시물을 볼 경우 가중치가 안오르게 하는 서비스 추가

[ feat ]: 새벽 12:00 기준, 넘기 전엔 다시 게시물을 볼 경우 가중치가 안오르게 하는 서비스 추가

---

drrr-api/src/main/java/com/drrr/recommand/service/impl/ExternalMemberPostReadService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/MemberPreferredCategoryServiceModificationService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/MemberViewWeightService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/RecommendPostService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/WeightValidationService.java
drrr-domain/src/main/java/com/drrr/domain/email/service/VerificationService.java
drrr-domain/src/main/java/com/drrr/domain/like/service/TechBlogPostLikeService.java
drrr-domain/src/main/java/com/drrr/domain/log/service/LogUpdateService.java
drrr-domain/src/test/java/com/drrr/domain/member/service/MemberViewWeightServiceTest.java
drrr-infra/src/main/java/com/drrr/infra/notifications/kafka/config/KafkaConfig.java
drrr-infra/src/main/java/com/drrr/infra/notifications/kafka/email/EmailConsumer.java
drrr-infra/src/main/java/com/drrr/infra/notifications/kafka/webpush/WebPushConsumer.java

[ refactor ] : 로그 통합 

---

drrr-domain/src/main/java/com/drrr/domain/category/service/InitializeWeightService.java

회원가입 시 카테고리 가중치 테이블에 마지막으로 읽은 시간도 같이 초기화

[ fix ]: 게시물 추천 버그 고침

---

drrr-api/src/main/java/com/drrr/recommand/service/impl/ExternalRecommendService.java
drrr-domain/src/main/java/com/drrr/domain/like/service/TechBlogPostLikeService.java

-  post controller api 관련 리팩토링 반영

[ refactor] : post controller api 관련 리팩토링 반영

---

drrr-api/src/main/java/com/drrr/auth/payload/request/KakaoOAuth2Request.java
drrr-api/src/main/java/com/drrr/auth/payload/request/SignUpRequest.java

[ fix ]: 프로파일 이미지 url 제대로 초기화 못하는 문제 해결

fix: 프로파일 이미지 url 제대로 초기화 못하는 문제 해결

---

drrr-domain/src/test/java/com/drrr/domain/category/service/WeightValidationServiceTest.java
drrr-domain/src/test/java/com/drrr/domain/util/DatabaseCleaner.java

[ chore ] : 필요없는 콘솔 output 제거

---

drrr-domain-redis/src/main/java/com/drrr/domain/category/entity/RedisCategoryPosts.java
drrr-domain-redis/src/main/java/com/drrr/domain/category/service/RedisCategoryService.java
drrr-domain-redis/src/main/java/com/drrr/domain/redis/config/RedisConfig.java

[ feat ]: redis에 카테고리와 날짜에 따른 게시물들을 가져오는 서비스 추가

feat: redis에 카테고리와 날짜에 따른 게시물들을 가져오는 서비스 추가

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java

fix : 조회 api의 method type 변경

---

drrr-api/src/main/java/com/drrr/web/exception/ApiExceptionCode.java
drrr-api/src/main/java/com/drrr/web/security/filter/JwtTokenValidationFilter.java

fix: public api 경우 jwt 토큰이 담겨져 있으면 서버 에러가 나는 부분 수정

[ fix ]: public api 경우 jwt 토큰이 담겨져 있으면 서버 에러가 나는 부분 수정

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalCategoryService.java
drrr-api/src/test/java/com/drrr/category/CategoryE2ETest.java
drrr-domain/src/main/java/com/drrr/domain/category/dto/CategoryDto.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryService.java

[ feat ] : 사용자 id로 선호하는 카테고리를 가져오는 api 추가

feat : 사용자 id로 선호하는 카테고리를 가져오는 api 추가

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostService.java
drrr-api/src/test/java/com/drrr/techblogpost/TechBlogPostE2ETest.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/dto/TechBlogPostOuterDto.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/TechBlogPostRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/service/TechBlogPostService.java

[ feat ] : slice와 page를 이용한 무한 스크롤을 위한 api 제공

[ feat ] : slice와 page를 이용한 무한 스크롤을 위한 api 제공

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java

[ chore ] : 카테고리 api 관련 swagger 문서 보완

docs: 카테고리 api 관련 swagger 문서 보완

---

drrr-api/src/main/java/com/drrr/alarm/controller/PushAlarmController.java
drrr-api/src/main/java/com/drrr/alarm/service/impl/ExternalMemberWebPushPostsService.java
drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CategoryWeightRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/dto/TechBlogPostOuterDto.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/custom/CustomTechBlogPostCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/custom/CustomTechBlogPostCategoryRepositoryImpl.java

[ feat ] : 사용자의 오늘날의 푸시 알림에 해당하는 게시물 반환하는 api 추가](https://github.com/side-proejct/backend/pull/102)

 [ feat ] : 사용자의 오늘날의 푸시 알림에 해당하는 게시물 반환하는 api 추가

---

drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryWeightRepositoryImpl.java

[ refactor ] : change to String.value

refactor: change to String.value

---

drrr-api/src/main/java/com/drrr/alarm/controller/PushAlarmController.java
drrr-api/src/main/java/com/drrr/alarm/service/impl/ExternalMemberWebPushPostsService.java
drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-api/src/main/java/com/drrr/techblogpost/request/TechBlogPostSliceRequest.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostLikeService.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostService.java
drrr-api/src/test/java/com/drrr/techblogpost/TechBlogPostE2ETest.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/dto/TechBlogPostBasicInfoDto.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/dto/TechBlogPostDetailedInfoDto.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/CustomTechBlogPostRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/custom/CustomTechBlogPostCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/custom/CustomTechBlogPostCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/impl/CustomTechBlogPostRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/service/TechBlogPostService.java

특정 카테고리에 대한 게시물 가져오는 api에서 모든 게시물을 가져오는 게 아닌 slice와 page를 이용해서 가져오게 수정

feat : 특정 카테고리에 대한 게시물 가져오는 api 수정

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-api/src/main/java/com/drrr/techblogpost/request/TechBlogPostSliceRequest.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalPostDislikeService.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalPostLikeService.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostService.java
drrr-core/src/main/java/com/drrr/core/techblogpost/constant/ProcessConstants.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/dto/TechBlogPostBasicInfoDto.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/TechBlogPostRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/service/TechBlogPostService.java

[feat: page 정보에 대한 디폴트 값 설정 및 정렬 디폴트 정보를 writtenAt로 수정](https://github.com/side-proejct/backend/commit/bee551d11c38b8e85fb23ca17dd7ef6d4876a5f4)

feat: page 정보에 대한 디폴트 값 설정 및 정렬 디폴트 정보를 writtenAt로 수정

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/request/CategorySliceRequest.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalCategoryService.java
drrr-api/src/test/java/com/drrr/category/CategoryE2ETest.java
drrr-domain/src/main/java/com/drrr/domain/category/dto/CategoryDto.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CategoryWeightRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryService.java

feat: 카테고리를 가져오는 api에서 slice와 page 기능 추가

feat: 카테고리를 가져오는 api에서 slice와 page 기능 추가

---

drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/impl/CustomTechBlogPostRepositoryImpl.java

refactor: deprecated 된 fetchCount() 대신 fetchOne() 사용

refactor: deprecated 된 fetchCount() 대신 fetchOne() 사용

---

drrr-core/src/main/java/com/drrr/core/recommandation/constant/DaysConstants.java
drrr-core/src/main/java/com/drrr/core/recommandation/constant/HoursConstants.java
drrr-core/src/main/java/com/drrr/core/recommandation/constant/PostConstants.java
drrr-core/src/main/java/com/drrr/core/recommandation/constant/WeightConstants.java
drrr-domain/src/main/java/com/drrr/domain/category/entity/CategoryWeight.java
drrr-domain/src/main/java/com/drrr/domain/category/service/InitializeWeightService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/MemberPreferredCategoryServiceModificationService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/MemberViewWeightService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/PostCategoryUtilityService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/RecommendPostService.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/custom/CustomTechBlogPostCategoryRepositoryImpl.java
drrr-domain/src/test/java/com/drrr/domain/category/service/CategoryModificationTest.java
drrr-domain/src/test/java/com/drrr/domain/category/service/WeightValidationServiceTest.java
drrr-domain/src/test/java/com/drrr/domain/member/service/MemberViewWeightServiceTest.java

chore: 의미없는 패키지 파일 제거 및 그 안에 파일 이동, 그에 따른 의존하는 파일의 패키지 수정

chore: 의미없는 패키지 파일 제거 및 그 안에 파일 이동, 그에 따른 의존하는 파일의 패키지 수정

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java

feat: jwt 없이 상세 기술 블로그를 조회할 수 있는 api 추가

feat: jwt 없이 상세 기술 블로그를 조회할 수 있는 api 추가

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalFindCategoryService.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryService.java

feat: 특정 기술 블로그에 해당하는 카테고리들의 정보 반환 api 추가

feat: 특정 기술 블로그에 해당하는 카테고리들의 정보 반환 api 추가

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/request/CategoryIndexSliceRequest.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalFindCategoryService.java
drrr-core/src/main/java/com/drrr/core/category/constant/IndexConstants.java
drrr-core/src/main/java/com/drrr/core/category/constant/LanguageConstants.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryService.java

feat: slice와 page를 이용해서 index에 해당하는 카테고리 정보 가져오기

feat: slice와 page를 이용해서 index에 해당하는 카테고리 정보 가져오기

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java

chore: swagger 문서 수정

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/request/CategoryIndexSliceRequest.java
drrr-api/src/main/java/com/drrr/category/request/CategorySliceRequest.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalCategoryService.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalFindCategoryService.java
drrr-core/src/main/java/com/drrr/core/category/constant/IndexConstants.java

refactor: Get 메서드에 RequestBody 제거 후 @ModelAttribute로 변경 후 request 클래스 record로 변경

refactor: Get 메서드에 RequestBody 제거 후 @ModelAttribute로 변경 후 request 클래스 record로 변경

---

drrr-api/src/main/java/com/drrr/error/GlobalExceptionHandler.java

feat: RuntimeException global exception 추가

feat: RuntimeException global exception 추가

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryService.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/dto/TechBlogPostBasicInfoDto.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/dto/TechBlogPostCategoryDto.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/CustomTechBlogPostRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/TechBlogPostRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/impl/CustomTechBlogPostRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/service/TechBlogPostService.java

feat: 모든 블로그를 가져오는 API와 특정 카테고리에 해당하는 블로그를 가져오는 API에 카테고리 정보도 추가

feat: 모든 블로그를 가져오는 API와 특정 카테고리에 해당하는 블로그를 가져오는 API에 카테고리 정보도 추가

---

drrr-infra/src/main/java/com/drrr/infra/push/entity/PushPost.java
drrr-infra/src/main/java/com/drrr/infra/push/entity/PushStatus.java
drrr-infra/src/main/java/com/drrr/infra/push/repository/PushPostRepository.java
drrr-infra/src/main/java/com/drrr/infra/push/repository/PushStatusRepository.java

feat: 과거 푸시 알림을 기록할 수 있는 엔티티 파일 및 리포지토리 추가

feat: 과거 푸시 알림을 기록할 수 있는 엔티티 파일 및 리포지토리 추가

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java

refactor: swagger 문서 설명 추가

---

drrr-api/src/main/java/com/drrr/category/service/impl/ExternalCategoryService.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalFindCategoryService.java
drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryService.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/service/TechBlogPostService.java

refactor : exception 제거

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/request/CategorySearchWordRequest.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalSearchCategoryService.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java

feat: 카테고리 검색 api 추가

---

drrr-api/src/main/java/com/drrr/alarm/controller/PushAlarmController.java
drrr-api/src/main/java/com/drrr/auth/controller/AuthController.java
drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/recommand/controller/MemberPostWeightController.java
drrr-api/src/main/java/com/drrr/web/annotation/JwtToken.java
drrr-api/src/main/java/com/drrr/web/annotation/MemberId.java
drrr-api/src/main/java/com/drrr/web/config/WebConfig.java
drrr-api/src/main/java/com/drrr/web/exception/ApiExceptionCode.java
drrr-api/src/main/java/com/drrr/web/jwt/util/JwtProvider.java
drrr-api/src/main/java/com/drrr/web/resolver/JwtTokenResolver.java

feat: jwt resolver, memberId를 가져오는 커스텀 어노테이션 추가

feat: jwt resolver, memberId를 가져오는 커스텀 어노테이션 추가

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/impl/CustomTechBlogPostRepositoryImpl.java

refactor: post에 해당하는 카테고리를 가져오는 부분 최적화

refactor: post에 해당하는 카테고리를 가져오는 부분 최적화

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-api/src/main/java/com/drrr/techblogpost/dto/TechBlogPostIndexSliceRequest.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostSearchService.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/CustomTechBlogPostRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/impl/CustomTechBlogPostRepositoryImpl.java
drrr-push-batch/build.gradle

feat: 블로그 제목으로 검색하는 api 추가

---

drrr-api/src/main/java/com/drrr/auth/controller/AuthController.java

chore: request mapping에 /api/v1 추가

chore: request mapping에 /api/v1 추가

---

drrr-api/src/main/java/com/drrr/recommand/controller/RecommendController.java
drrr-api/src/test/java/com/drrr/recommend/RecommendServiceE2ETest.java

feat: @PostMapping -> @GetMapping으로 수정

feat: @PostMapping -> @GetMapping으로 수정

---

drrr-api/src/main/java/com/drrr/web/security/filter/JwtTokenValidationFilter.java

feat: 에러 메시지에서 한글 깨지는 것 수정 -> UTF-8 설정

feat: 에러 메시지에서 한글 깨지는 것 수정 -> UTF-8 설정

---

drrr-api/src/main/java/com/drrr/member/controller/MemberController.java
drrr-api/src/main/java/com/drrr/member/service/ExternalMemberService.java
drrr-domain/src/main/java/com/drrr/domain/exception/DomainExceptionCode.java
drrr-domain/src/main/java/com/drrr/domain/member/dto/MemberDto.java
drrr-domain/src/main/java/com/drrr/domain/member/repository/CustomMemberRepository.java
drrr-domain/src/main/java/com/drrr/domain/member/repository/MemberRepository.java
drrr-domain/src/main/java/com/drrr/domain/member/repository/impl/CustomMemberRepositoryImpl.java

feat: 사용자 정보 반환하는 api 추가

---

drrr-api/src/main/java/com/drrr/recommand/service/impl/ExternalMemberPostReadService.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CategoryWeightRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/service/MemberViewWeightService.java
drrr-domain/src/main/java/com/drrr/domain/log/service/LogUpdateService.java
drrr-domain/src/main/java/com/drrr/domain/log/service/MemberPostLogService.java

fix: 사용자 게시물 읽음 api 버그 픽스

---

drrr-api/src/main/java/com/drrr/member/controller/MemberController.java
drrr-api/src/main/java/com/drrr/member/dto/PostReadCheckDto.java
drrr-api/src/main/java/com/drrr/member/service/ExternalMemberPostReadCheckService.java
drrr-api/src/main/java/com/drrr/member/service/ExternalMemberService.java
drrr-domain/src/main/java/com/drrr/domain/log/repository/MemberPostLogRepository.java

feat: 사용자 게시물 읽음 여부 반환 api 추가

---

drrr-api/src/main/java/com/drrr/auth/controller/AuthController.java
drrr-api/src/main/java/com/drrr/auth/payload/request/SignOutRequest.java
drrr-api/src/main/java/com/drrr/auth/service/impl/IssuanceTokenService.java
drrr-api/src/main/java/com/drrr/web/jwt/util/JwtProvider.java
drrr-domain-redis/src/main/java/com/drrr/domain/auth/service/AuthenticationTokenService.java

feat: signout api 생성

---

drrr-api/src/main/java/com/drrr/alarm/service/impl/ExternalMemberSubscriptionService.java
drrr-api/src/test/java/com/drrr/push/PushE2ETest.java
drrr-domain/src/main/java/com/drrr/domain/exception/DomainExceptionCode.java
drrr-infra/src/main/java/com/drrr/infra/push/repository/PushStatusRepository.java
drrr-infra/src/main/java/com/drrr/infra/push/repository/SubscriptionRepository.java

test: Push 관련 e2e 테스트 추가

---

.github/workflows/develop-pr.yml
drrr-api/src/test/java/com/drrr/auth/AuthE2ETest.java

test: auth관련 e2e 테스트

---

drrr-api/src/test/java/com/drrr/category/CategoryE2ETest.java

test: category api 관련 e2e 테스트 추가

test: category api 관련 e2e 테스트 추가

---

drrr-api/src/main/java/com/drrr/error/GlobalExceptionHandler.java

feat: 서버 에러 관련 global exception 추가

feat: 서버 에러 관련 global exception 추가

---

drrr-api/src/main/resources/application-develop.yml

refactor: db option allowPublicKeyRetrieval 추가

refactor: db option allowPublicKeyRetrieval 추가

---

drrr-domain/src/main/java/com/drrr/domain/techblogpost/dto/TechBlogPostDetailedInfoDto.java

feat: 게시물 상세보기 반환 필드 추가

---

drrr-api/src/main/java/com/drrr/recommand/controller/RecommendController.java
drrr-api/src/main/java/com/drrr/recommand/service/impl/ExternalRecommendService.java
drrr-api/src/test/java/com/drrr/recommend/RecommendServiceE2ETest.java
drrr-domain/src/main/java/com/drrr/domain/category/service/RecommendPostService.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/CustomTechBlogPostRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/impl/CustomTechBlogPostRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/service/TechBlogPostService.java

feat: 추천 게시물 반환 타입 변경

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/LikeController.java
drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostLikeService.java
drrr-api/src/main/java/com/drrr/web/config/WebConfig.java
drrr-api/src/main/java/com/drrr/web/converter/StringToTopTechBlogTypeConverter.java
drrr-api/src/test/java/com/drrr/techblogpost/TechBlogPostE2ETest.java
drrr-core/src/main/java/com/drrr/core/code/techblog/TopTechBlogType.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/CustomTechBlogPostRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/impl/CustomTechBlogPostRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/service/TechBlogPostService.java

feat: 탑 게시물 가져오는 API 통합, 좋아요 controller 분리, 좋아요 테스트 감량화

feat: 탑 게시물 가져오는 API 통합, 좋아요 controller 분리, 좋아요 테스트 감량화

---

drrr-api/src/main/java/com/drrr/web/config/WebConfig.java
drrr-api/src/main/java/com/drrr/web/converter/LanguageConverter.java
drrr-api/src/main/java/com/drrr/web/converter/SortDirectionConverter.java
drrr-api/src/main/java/com/drrr/web/converter/TopTechBlogTypeConverter.java
drrr-api/src/test/java/com/drrr/member/MemberViewE2ETest.java
drrr-core/src/main/java/com/drrr/core/code/member/Gender.java
drrr-domain/src/test/java/com/drrr/domain/recommend/service/data/DummyDataFactory.java

feat: 대소문자 구별없애는 converter 추가 및 필요없는 enum 제거

feat: 대소문자 구별없애는 converter 추가 및 필요없는 enum 제거

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/LikeController.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalPostDislikeService.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalPostLikeService.java
drrr-api/src/test/java/com/drrr/techblogpost/TechBlogPostE2ETest.java

refactor: 좋아요와 좋아요 해제 api 요청 시 body 제거

refactor: 좋아요와 좋아요 해제 api 요청 시 body 제거

---

drrr-api/src/main/java/com/drrr/alarm/controller/PushAlarmController.java
drrr-api/src/main/java/com/drrr/auth/controller/AuthController.java
drrr-api/src/main/java/com/drrr/auth/controller/EmailController.java
drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/request/CategorySearchWordRequest.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalSearchCategoryService.java
drrr-api/src/main/java/com/drrr/member/controller/MemberController.java
drrr-api/src/main/java/com/drrr/recommand/controller/MemberPostWeightController.java
drrr-api/src/main/java/com/drrr/recommand/controller/RecommendController.java
drrr-api/src/main/java/com/drrr/techblogpost/controller/LikeController.java
drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-api/src/main/java/com/drrr/techblogpost/dto/TechBlogPostIndexSliceRequest.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostSearchService.java
drrr-api/src/test/java/com/drrr/auth/AuthE2ETest.java
drrr-api/src/test/java/com/drrr/category/CategoryE2ETest.java
drrr-api/src/test/java/com/drrr/member/MemberViewE2ETest.java
drrr-api/src/test/java/com/drrr/push/PushE2ETest.java
drrr-api/src/test/java/com/drrr/recommend/RecommendServiceE2ETest.java
drrr-api/src/test/java/com/drrr/techblogpost/TechBlogPostE2ETest.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/CustomTechBlogPostRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/impl/CustomTechBlogPostRepositoryImpl.java

feat: 모든 controller api url, swagger 및 requestbody의 필드명 변경

feat: 모든 controller api url, swagger 및 requestbody의 필드명 변경

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java

refactor: api 스웨거 문서 보강

---

drrr-api/src/main/java/com/drrr/auth/service/impl/IssuanceVerificationCode.java

fix: 이메일 중복 에러 변경

---

drrr-domain/src/main/java/com/drrr/domain/category/repository/CategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java

refactor: Querydsl에서 JPQL로 변경

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/request/CategoryRangeRequest.java
drrr-api/src/main/java/com/drrr/category/request/CategoryRequest.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalFindCategoryService.java
drrr-api/src/main/java/com/drrr/web/config/WebConfig.java
drrr-api/src/main/java/com/drrr/web/converter/IndexConverter.java
drrr-core/src/main/java/com/drrr/core/category/constant/IndexConstants.java
drrr-domain/src/main/java/com/drrr/domain/category/dto/CategoryRangeDto.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryService.java

feat: index 범위 지정을 지정해서 카테고리를 각각 index에 맞게 반환하는 api 추가

feat: index 범위 지정을 지정해서 카테고리를 각각 index에 맞게 반환하는 api 추가

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/request/CategoryRangeRequest.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalFindCategoryService.java
drrr-domain/src/main/java/com/drrr/domain/category/dto/CategoryRangeDto.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryService.java
drrr-domain/src/main/java/com/drrr/domain/exception/DomainExceptionCode.java

feat: 기타 카테고리 가져오는 api  및 request 검증 추가

feat: 기타 카테고리 가져오는 api  및 request 검증 추가

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-api/src/main/java/com/drrr/techblogpost/dto/TechBlogPostIndexSliceRequest.java
drrr-api/src/main/java/com/drrr/techblogpost/request/TechBlogPostSliceRequest.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostSearchService.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/MemberViewWeightService.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/TechBlogPostRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/impl/CustomTechBlogPostRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/service/TechBlogPostService.java
drrr-domain/src/test/java/com/drrr/domain/recommend/service/RecommendServiceTest.java

[refactor: Slice Api에서 Sort 제거 -> 작성일자 기준 내림차순으로 반환 디폴트 설정](https://github.com/side-proejct/backend/pull/166)

 refactor: Slice Api에서 Sort 제거 -> 작성일자 기준 내림차순으로 반환 디폴트 설정

---

drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/impl/CustomTechBlogPostRepositoryImpl.java

feat: 인덱스 검색 시 대소문자 구분 없애기

---

drrr-api/src/main/java/com/drrr/recommand/service/impl/ExternalRecommendService.java
drrr-domain/src/main/java/com/drrr/domain/log/repository/CustomMemberPostLogRepository.java
drrr-domain/src/main/java/com/drrr/domain/log/repository/impl/CustomMemberPostLogRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/log/service/LogUpdateService.java

refactor: 메서드 명 변경

---

drrr-api/src/main/java/com/drrr/recommand/controller/RecommendController.java
drrr-api/src/main/java/com/drrr/recommand/service/impl/ExternalRecommendService.java
drrr-api/src/test/java/com/drrr/recommend/RecommendServiceE2ETest.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/category/service/PostCategoryUtilityService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/RecommendPostService.java
drrr-domain/src/main/java/com/drrr/domain/log/repository/CustomMemberPostLogRepository.java
drrr-domain/src/main/java/com/drrr/domain/log/repository/impl/CustomMemberPostLogRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/log/service/LogUpdateService.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/CustomTechBlogPostRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/custom/CustomTechBlogPostCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/custom/CustomTechBlogPostCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/impl/CustomTechBlogPostRepositoryImpl.java
drrr-domain/src/test/java/com/drrr/domain/recommend/service/RecommendServiceTest.java
drrr-infra/src/main/java/com/drrr/infra/notifications/kafka/email/EmailProducer.java

feat: 게시물 추천 API에서 count PathVariable 추가, 그에 다른 반영
- 게시물 개수 지정

feat: 게시물 추천 API 로직 추가

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/entity/RedisAllPostCategoriesSlice.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java

refactor: 모든 게시물 가져오는 api 리팩토링

refactor: 모든 게시물 가져오는 api 리팩토링

---

drrr-domain/src/main/java/com/drrr/domain/category/entity/CategoryWeight.java
drrr-domain/src/test/java/com/drrr/domain/category/service/WeightValidationServiceTest.java

fix: 가중치 검증 로직 버그 수정

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java

fix: 사이즈 만큼 기타 카테고리를 가져오게끔 limit 쿼리 추가

fix: 사이즈 만큼 기타 카테고리를 가져오게끔 limit 쿼리 추가

---

docker-compose.yml
drrr-api/build.gradle
drrr-api/src/test/java/com/drrr/util/DatabaseCleaner.java
drrr-domain/build.gradle
drrr-domain/src/test/java/com/drrr/domain/fixture/category/CategoryFixture.java
drrr-domain/src/test/java/com/drrr/domain/fixture/category/weight/CategoryWeightFixture.java
drrr-domain/src/test/java/com/drrr/domain/fixture/member/MemberFixture.java
drrr-domain/src/test/java/com/drrr/domain/fixture/post/TechBlogPostCategoryFixture.java
drrr-domain/src/test/java/com/drrr/domain/fixture/post/TechBlogPostFixture.java
drrr-domain/src/test/java/com/drrr/domain/techblogpost/service/FindPostServiceTest.java
drrr-domain/src/test/java/com/drrr/domain/util/DatabaseCleaner.java

test: fixture 클래스 추가 및 gradle 의존성 수정 -> drrr-domain 모듈의 test 패키지에 작성된 클래스를 drrr-api test 패키지에서 의존하게 변경

test: fixture 클래스 추가 및 gradle 의존성 수정 

---

docker-compose.yml
drrr-api/src/main/java/com/drrr/recommand/service/impl/ExternalMemberPostReadService.java
drrr-core/src/main/java/com/drrr/core/recommandation/constant/WeightConstants.java
drrr-domain/src/main/java/com/drrr/domain/category/entity/CategoryWeight.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CategoryWeightRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryWeightService.java
drrr-domain/src/main/java/com/drrr/domain/category/service/MemberViewWeightService.java
drrr-domain/src/test/java/com/drrr/domain/member/service/MemberViewWeightServiceTest.java

fix: 가중치 관련 버그 수정 및 사용자 게시글 읽었을 때 호출하는 api 서비스 분리

fix: 가중치 관련 버그 수정 및 사용자 게시글 읽었을 때 호출하는 api 서비스 분리

---

drrr-api/src/main/java/com/drrr/auth/payload/request/GithubOAuth2Request.java

fix: clientId 초기화 코드 추가

---

drrr-domain/src/main/java/com/drrr/domain/category/service/WeightValidationService.java
drrr-domain/src/main/java/com/drrr/domain/log/service/LogUpdateService.java

fix: 마지막 읽은시간 초기화 누락 해결

---

drrr-domain/src/main/java/com/drrr/domain/log/entity/post/MemberPostLog.java
drrr-domain/src/main/java/com/drrr/domain/log/service/LogUpdateService.java

fix: read status 업데이트 함수 추가

---

drrr-api/src/main/java/com/drrr/alarm/controller/PushAlarmController.java
drrr-api/src/main/java/com/drrr/alarm/controller/WebPushTestController.java
drrr-api/src/main/java/com/drrr/alarm/service/impl/ExternalPushStatusUpdateService.java
drrr-api/src/main/java/com/drrr/alarm/service/impl/ExternalSubscriptionDeleteService.java
drrr-api/src/main/java/com/drrr/alarm/service/impl/ExternalWebPushTestService.java
drrr-api/src/main/java/com/drrr/alarm/service/request/PushDatesRequest.java
drrr-infra/src/main/java/com/drrr/infra/notifications/kafka/webpush/WebPushProducer.java
drrr-infra/src/main/java/com/drrr/infra/push/repository/PushStatusRepository.java
drrr-infra/src/main/java/com/drrr/infra/push/repository/SubscriptionRepository.java
drrr-infra/src/main/java/com/drrr/infra/push/repository/impl/CustomPushStatusRepositoryImpl.java

feat: 푸시 테시트 시뮬레이션을 위해 controller 수정 및 pushController 버그 픽스

feat: 푸시 테시트 시뮬레이션을 위해 controller 수정 및 pushController 버그 픽스

---

drrr-api/src/main/java/com/drrr/auth/payload/request/SignUpRequest.java
drrr-api/src/main/java/com/drrr/error/GlobalExceptionHandler.java
drrr-api/src/main/java/com/drrr/member/controller/MemberController.java
drrr-api/src/main/java/com/drrr/member/payload/request/ProfileUpdateRequest.java
drrr-api/src/main/java/com/drrr/member/service/ExternalMemberService.java
drrr-domain/src/main/java/com/drrr/domain/member/entity/Member.java
drrr-domain/src/main/java/com/drrr/domain/member/repository/MemberRepository.java
drrr-domain/src/main/java/com/drrr/domain/member/service/MemberProfileUpdateService.java

feat: 사용자의 프로필 변경 -> 이메일 혹은 닉네임 변경 API 추가

feat: 사용자의 프로필 변경 -> 이메일 혹은 닉네임 변경 API 추가

---

drrr-domain/src/main/java/com/drrr/domain/member/repository/CustomMemberRepository.java
drrr-domain/src/main/java/com/drrr/domain/member/repository/MemberRepository.java
drrr-domain/src/main/java/com/drrr/domain/member/repository/impl/CustomMemberRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/member/service/MemberProfileUpdateService.java

feat: 사용자 프로필 수정 api 수정

---

drrr-api/src/test/java/com/drrr/member/MemberViewE2ETest.java
drrr-api/src/test/java/com/drrr/recommend/RecommendServiceE2ETest.java
drrr-api/src/test/java/com/drrr/techblogpost/TechBlogPostE2ETest.java
drrr-domain/src/main/java/com/drrr/domain/log/entity/post/MemberPostLog.java
drrr-domain/src/main/java/com/drrr/domain/log/repository/impl/CustomMemberPostLogRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/log/service/LogUpdateService.java
drrr-domain/src/test/java/com/drrr/domain/recommend/service/RecommendServiceTest.java
drrr-domain/src/test/java/com/drrr/domain/recommend/service/data/DummyDataFactory.java

feat: MemberPostLog 엔티티에 RecommendedAt 필드 추가, 게시물 추천 시 당일 추천했던 게시물을 반환하기 위한 조건

feat: MemberPostLog 엔티티에 RecommendedAt 필드 추가

---

drrr-api/src/main/java/com/drrr/techblogpost/controller/LikeController.java
drrr-api/src/main/java/com/drrr/techblogpost/response/MemberLikedPostsResponse.java
drrr-api/src/test/java/com/drrr/techblogpost/TechBlogPostE2ETest.java
drrr-domain/src/main/java/com/drrr/domain/like/repository/TechBlogPostLikeRepository.java

feat: 사용자의 좋아요한 게시물 id 정보 반환 api 추가

feat: 사용자의 좋아요한 게시물 id 정보 반환 api 추가

---

.github/workflows/master-merge.yml
drrr-api/src/main/java/com/drrr/DrRRApiApplication.java
drrr-api/src/main/java/com/drrr/web/config/TimeZoneConfig.java
drrr-api/src/main/resources/application-develop.yml
drrr-api/src/main/resources/application.yml
drrr-api/src/test/resources/application.yml
drrr-domain-redis/src/main/java/com/drrr/domain/config/RedisConfig.java
drrr-infra/src/main/java/com/drrr/infra/config/OtelConfiguration.java

feat: aws를 위한 master에 올라갈 설정 정보들 추가

feat: aws를 위한 master에 올라갈 설정 정보들 추가

---

drrr-api/src/main/java/com/drrr/techblogpost/response/TechBlogPostResponse.java
drrr-api/src/test/java/com/drrr/recommend/RecommendServiceE2ETest.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/dto/TechBlogPostViewDto.java

feat: response 객체 수정

---

drrr-api/src/main/java/com/drrr/alarm/controller/PushAlarmController.java
drrr-api/src/main/java/com/drrr/alarm/service/impl/ExternalSearchPushPostsService.java
drrr-api/src/main/java/com/drrr/recommand/controller/RecommendController.java

feat: swagger 수정 및 response 타입 수정

feat: swagger 수정 및 response 타입 수정

---

drrr-api/src/main/java/com/drrr/alarm/service/impl/ExternalSearchPushPostsService.java
drrr-api/src/main/java/com/drrr/check/controller/HealthCheckController.java
drrr-api/src/main/java/com/drrr/recommand/service/impl/ExternalRecommendService.java
drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-api/src/main/java/com/drrr/techblogpost/response/TechBlogPostResponse.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalPostDislikeService.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalPostLikeService.java
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostService.java
drrr-api/src/main/java/com/drrr/web/annotation/Optional.java
drrr-api/src/main/java/com/drrr/web/resolver/JwtTokenResolver.java
drrr-api/src/test/java/com/drrr/techblogpost/TechBlogPostE2ETest.java
drrr-domain-redis/src/main/java/com/drrr/domain/recommend/service/RedisRecommendationService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/cache/entity/RedisMemberPostDynamicData.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/cache/entity/RedisPostDynamicData.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/cache/payload/RedisSlicePostsContents.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/constant/RedisMemberConstants.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/constant/RedisTtlConstants.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/event/RedisPostsEventListener.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/DynamicDataService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java
drrr-domain/src/main/java/com/drrr/domain/like/entity/TechBlogPostLike.java
drrr-domain/src/main/java/com/drrr/domain/like/repository/TechBlogPostLikeRepository.java
drrr-domain/src/main/java/com/drrr/domain/like/service/TechBlogPostLikeService.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/common/TechBlogPostQueryService.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/service/TechBlogPostService.java

feat: 사용자 좋아요 여부를 TechBlogPostResponse 안에 추가

feat: 사용자 좋아요 여부를 TechBlogPostResponse 안에 추가

---

drrr-api/src/main/java/com/drrr/web/config/WebConfig.java
drrr-api/src/main/java/com/drrr/web/interceptor/RateLimitInterceptor.java
drrr-api/src/test/java/com/drrr/auth/AuthE2ETest.java
drrr-api/src/test/java/com/drrr/category/CategoryE2ETest.java
drrr-api/src/test/java/com/drrr/member/MemberViewE2ETest.java
drrr-api/src/test/java/com/drrr/recommend/RecommendServiceE2ETest.java
drrr-api/src/test/java/com/drrr/techblogpost/TechBlogPostE2ETest.java
drrr-domain-redis/src/main/java/com/drrr/domain/rate/service/RateLimiterService.java
drrr-domain-redis/src/main/java/com/drrr/domain/recommend/service/RedisRecommendationService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/cache/entity/RedisPostDynamicData.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/event/RedisPostsEventListener.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/DynamicDataService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java
drrr-domain/src/test/java/com/drrr/domain/recommend/service/RecommendServiceTest.java

feat: ddos 공격 방어 코드 및 사용자 좋아요 여부 가져오는 함수 분리

feat: ddos 공격 방어 코드 및 사용자 좋아요 여부 가져오는 함수 분리

---

drrr-api/src/main/java/com/drrr/web/interceptor/RateLimitInterceptor.java

feat: 일시적으로 request 수 증가

---

drrr-api/src/main/java/com/drrr/web/interceptor/RateLimitInterceptor.java

feat: 운영에서 ip를 제대로 가져오는지 확인용

---

.github/workflows/master-merge.yml

feat: 임시 액션 수정

---

.github/workflows/master-merge.yml

feat: github action master 파일 워크플로우 수정

feat: github action master 파일 워크플로우 수정

---

.github/workflows/master-merge.yml

feat: master-merge 수정

---

.github/workflows/master-merge.yml

feat: master-merge 파일 수정

---

drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostService.java
drrr-domain-redis/src/main/java/com/drrr/domain/config/RedisConfig.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java

feat: 테이블명 소문자로 변경

---

.github/workflows/master-merge.yml
drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostService.java
drrr-domain-redis/src/main/java/com/drrr/domain/config/RedisConfig.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java

fix: 카테고리에 해당하는 블로그 가져오는 api fix

fix: 카테고리에 해당하는 블로그 가져오는 api fix

---

drrr-domain-redis/src/main/java/com/drrr/domain/recommend/service/RedisRecommendationService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/DynamicDataService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java

feat: 추천 게시물 api 호출 시 동적 데이터도 save하게끔 변경

feat: 추천 게시물 api 호출 시 동적 데이터도 save하게끔 변경

---

drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java

feat: 에러 찾기 위해서 테스트

---

drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java

feat: 버그 확인용

---

build.gradle
drrr-api/src/main/resources/application-develop.yml
drrr-domain-redis/src/main/java/com/drrr/domain/recommend/service/RedisRecommendationService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/cache/entity/RedisTechBlogPostsCategoriesStaticData.java

feat: discord 알림 추가 및 ttl 변경

---

drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java

feat: 운영 로그 확인용

---

drrr-api/src/main/resources/logback.xml

feat: 디스코드 로그백 추가

---

drrr-api/src/main/java/com/drrr/redis/controller/RedisController.java
drrr-domain-redis/src/main/java/com/drrr/domain/util/CacheFlushUtils.java

feat: cache flushall api 추가

---

drrr-api/src/main/java/com/drrr/redis/controller/RedisController.java

feat: redis flushall api 추가

---

drrr-api/src/main/java/com/drrr/recommand/service/impl/ExternalMemberPostReadService.java
drrr-api/src/main/java/com/drrr/recommand/service/impl/ExternalRecommendService.java
drrr-domain-redis/src/main/java/com/drrr/domain/recommend/service/RedisRecommendationService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/event/RedisPostsEventListener.java

feat: 추천 게시물 캐싱 에러 fix

---

drrr-api/src/test/java/com/drrr/recommend/RecommendServiceE2ETest.java
drrr-api/src/test/java/com/drrr/techblogpost/TechBlogPostE2ETest.java
drrr-domain-redis/src/main/java/com/drrr/domain/recommend/service/RedisRecommendationService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/event/RedisPostsEventListener.java
drrr-domain/src/test/java/com/drrr/domain/fixture/post/TechBlogPostFixture.java
drrr-domain/src/test/java/com/drrr/domain/fixture/post/TechBlogPostLikeFixture.java

feat: 추천 게시물 캐싱 로직 수정

---

drrr-api/src/main/java/com/drrr/web/discord/DiscordAppender.java
drrr-api/src/main/java/com/drrr/web/discord/util/ApiCallUtil.java

feat: 운영 확인용 로그 추가

---

drrr-api/src/main/java/com/drrr/web/discord/DiscordAppender.java

feat: 디스코드 메시지 숫자 줄임

---

drrr-api/src/main/java/com/drrr/web/discord/util/HttpRequestUtil.java

feat: header 정보 로직 수정

---

drrr-api/src/main/java/com/drrr/web/discord/util/HttpRequestUtil.java

feat: 대소문자 구분하는 거 다시 수정

---

drrr-api/src/main/java/com/drrr/web/discord/DiscordAppender.java
drrr-api/src/main/java/com/drrr/web/discord/util/ApiCallUtil.java

feat: 출력문 제거

---

drrr-api/src/main/java/com/drrr/web/discord/filter/MDCFilter.java

feat: ip 가져오는 헤더 설정

---

drrr-api/src/main/java/com/drrr/recommand/service/impl/ExternalRecommendService.java
drrr-api/src/test/java/com/drrr/recommend/RecommendServiceE2ETest.java
drrr-domain-redis/src/main/java/com/drrr/domain/recommend/service/RedisRecommendationService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/cache/entity/RedisPostDynamicData.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/DynamicDataService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java
drrr-domain-redis/src/test/java/com/drrr/domain/util/RedisTemplateTestUtil.java

feat: dynamic post data 로직 수정

---

drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/cache/entity/RedisPostDynamicData.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/DynamicDataService.java

feat: 로그 검사

---

drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/DynamicDataService.java

feat: 레디스 ttl초기화 로직 수정

---

drrr-domain-redis/src/main/java/com/drrr/domain/recommend/service/RedisRecommendationService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/cache/entity/RedisPostDynamicData.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/DynamicDataService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java

feat: redis 로직 수정

---

drrr-api/src/test/java/com/drrr/techblogpost/TechBlogPostE2ETest.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/event/RedisPostsEventListener.java

feat: test

---

drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/DynamicDataService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java

feat: redis 트랜잭션 추가

---

drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostService.java
drrr-api/src/main/java/com/drrr/web/discord/util/ApiCallUtil.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/DynamicDataService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java

feat: 출력문 다 제거 및 redis 수정

---

drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostService.java
drrr-api/src/main/java/com/drrr/techblogpost/service/SearchTopTechBlogPostService.java

feat: 탑 게시물 레디스 추가

---

drrr-api/src/main/java/com/drrr/auth/infrastructure/OAuth2/OAuth2Provider.java
drrr-api/src/main/java/com/drrr/web/exception/ApiExceptionCode.java
drrr-api/src/main/java/com/drrr/web/jwt/util/JwtProvider.java
drrr-api/src/main/java/com/drrr/web/security/filter/JwtTokenValidationFilter.java
drrr-domain/src/main/java/com/drrr/domain/exception/DomainExceptionCode.java

feat: jwt 토큰 로직 변경

---

drrr-api/src/main/java/com/drrr/auth/service/impl/IssuanceTokenService.java

feat: refresh token 로직으로 수정

---

drrr-api/src/main/java/com/drrr/error/GlobalExceptionHandler.java
drrr-api/src/main/java/com/drrr/web/security/filter/JwtTokenValidationFilter.java
drrr-api/src/test/java/com/drrr/auth/AuthE2ETest.java

feat: jwt 재발급 토큰에 대한 로직 수정

---

drrr-api/src/main/java/com/drrr/techblogpost/service/ExternalTechBlogPostService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java

feat: redis 수정

---

drrr-api/src/main/java/com/drrr/recommand/service/impl/ExternalRecommendService.java
drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostViewController.java
drrr-api/src/main/java/com/drrr/techblogpost/service/SearchTopTechBlogPostService.java
drrr-api/src/main/java/com/drrr/techblogpost/service/UnsignedMemberPostReadExternalService.java
drrr-api/src/main/java/com/drrr/web/page/request/PageableRequest.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/DynamicDataService.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java
drrr-domain-redis/src/test/java/com/drrr/domain/util/RedisTemplateTestUtil.java

feat: 추천 게시물 레디스 로직 수정

---

drrr-domain-redis/build.gradle

feat: redis 종속성 변경

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalFindCategoryService.java
drrr-api/src/main/java/com/drrr/web/page/request/CategoryIndexPageableRequest.java

feat: 카테고리 개수 요청 시 max length 200으로 변경

feat: 카테고리 개수 요청 시 max length 200으로 변경

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalSearchCategoryService.java

feat: MAX LENGTH를 늘린 pageRequest로 수정

feat: MAX LENGTH를 늘린 pageRequest로 수정

---

drrr-api/src/main/java/com/drrr/web/interceptor/RateLimitInterceptor.java
drrr-infra/src/main/java/com/drrr/infra/notifications/kafka/webpush/WebPushConsumer.java
drrr-infra/src/main/java/com/drrr/infra/notifications/kafka/webpush/WebPushProducer.java
drrr-infra/src/main/java/com/drrr/infra/push/entity/Subscription.java
drrr-infra/src/main/java/com/drrr/infra/push/repository/SubscriptionRepository.java

feat: 구독정보 엔티티 변경 및 rate 적용할 때 healthcheck는 무시

feat: 구독정보 엔티티 변경 및 rate 적용할 때 healthcheck는 무시

---

drrr-api/src/test/java/com/drrr/util/DatabaseCleaner.java

test: subscription 테이블은 id 컬럼을 지워서 DatabaseCleaner에서 제외 시킴

test: subscription 테이블은 id 컬럼을 지워서 DatabaseCleaner에서 제외 시킴

---

drrr-infra/src/main/java/com/drrr/infra/notifications/kafka/webpush/dto/NotificationDto.java
drrr-push-batch/src/main/java/com/drrr/push/config/PushMessageBatchConfig.java

feat: push batch에도 id 컬럼 없앤거 적용

feat: push batch에도 id 컬럼 없앤거 적용

---

drrr-api/src/main/java/com/drrr/alarm/controller/PushAlarmController.java
drrr-push-batch/src/main/java/com/drrr/push/config/PushMessageBatchConfig.java

feat: createdAt과 updatedAt 초기화 로직 추가

feat: createdAt과 updatedAt 초기화 로직 추가

---

drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java

feat: end index 수정

---

drrr-api/src/main/java/com/drrr/web/interceptor/RateLimitInterceptor.java
drrr-domain-redis/src/main/java/com/drrr/domain/rate/service/RateLimiterService.java

feat: api 별로 request 막는 기능 추가 api 횟수 제한

feat: api 별로 request 막는 기능 추가 api 횟수 제한

---

drrr-api/src/main/java/com/drrr/web/security/filter/JwtTokenValidationFilter.java

feat: ip 관련 로그 추가

---

drrr-api/src/main/java/com/drrr/auth/controller/EmailController.java
drrr-api/src/main/java/com/drrr/auth/payload/request/EmailRequest.java
drrr-api/src/main/java/com/drrr/auth/payload/request/EmailVerificationRequest.java
drrr-api/src/main/java/com/drrr/auth/service/impl/EmailVerificationService.java
drrr-api/src/main/java/com/drrr/auth/service/impl/IssuanceVerificationCode.java
drrr-core/src/main/java/com/drrr/core/category/constant/CategoryTypeConstants.java
drrr-domain-redis/src/main/java/com/drrr/domain/techblogpost/service/RedisTechBlogPostService.java
drrr-domain/src/main/java/com/drrr/domain/exception/DomainExceptionCode.java
drrr-fluent-crawler/src/test/java/com/drrr/study/PoolTest.java

feat: email 인증 관련 로직 수정

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/request/CategoryIndexSliceRequest.java
drrr-api/src/main/java/com/drrr/category/request/CategoryRangeRequest.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalFindCategoryService.java
drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-api/src/main/java/com/drrr/web/converter/LanguageConverter.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryService.java
drrr-domain/src/main/java/com/drrr/domain/email/service/VerificationService.java
drrr-domain/src/main/java/com/drrr/domain/exception/DomainExceptionCode.java
drrr-domain/src/main/java/com/drrr/domain/member/repository/MemberRepository.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/impl/CustomTechBlogPostRepositoryImpl.java
drrr-domain/src/test/java/com/drrr/domain/email/service/VerificationServiceTest.java

feat: member query 수정

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/request/CategoryIndexSliceRequest.java
drrr-api/src/main/java/com/drrr/category/request/CategoryRangeRequest.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalFindCategoryService.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryService.java

feat: category api 수정

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/request/CategoryIndexSliceRequest.java
drrr-api/src/main/java/com/drrr/category/request/CategoryRangeRequest.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalFindCategoryService.java
drrr-api/src/main/java/com/drrr/web/converter/LanguageConverter.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryService.java
drrr-domain/src/main/java/com/drrr/domain/email/service/VerificationService.java
drrr-domain/src/test/java/com/drrr/domain/email/service/VerificationServiceTest.java

feat: email 서비스 수정

---

drrr-api/src/main/java/com/drrr/category/controller/CategoryController.java
drrr-api/src/main/java/com/drrr/category/request/CategoryIndexSliceRequest.java
drrr-api/src/main/java/com/drrr/category/request/CategoryRangeRequest.java
drrr-api/src/main/java/com/drrr/category/service/impl/ExternalFindCategoryService.java
drrr-api/src/main/java/com/drrr/techblogpost/controller/TechBlogPostController.java
drrr-api/src/main/java/com/drrr/web/converter/LanguageConverter.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/CustomCategoryRepository.java
drrr-domain/src/main/java/com/drrr/domain/category/repository/impl/CustomCategoryRepositoryImpl.java
drrr-domain/src/main/java/com/drrr/domain/category/service/CategoryService.java
drrr-domain/src/main/java/com/drrr/domain/email/service/VerificationService.java
drrr-domain/src/main/java/com/drrr/domain/exception/DomainExceptionCode.java
drrr-domain/src/main/java/com/drrr/domain/techblogpost/repository/impl/CustomTechBlogPostRepositoryImpl.java
drrr-domain/src/test/java/com/drrr/domain/email/service/VerificationServiceTest.java

feat: post 서비스 수정

---

drrr-api/src/test/java/com/drrr/category/CategoryE2ETest.java

test: category test 수정
